export const EXERCISE_MEASUREMENTS = [
  { name: "assisted", count: "reps", measurement: "kg" },
  { name: "band", count: "reps", measurement: "kg" },
  { name: "barbell", count: "reps", measurement: "kg" },
  { name: "body weight", count: "reps", measurement: "kg" },
  { name: "bosu ball", count: "reps", measurement: "kg" },
  { name: "cable", count: "reps", measurement: "kg" },
  { name: "elliptical machine", count: "time", measurement: "km" },
  { name: "ez barbell", count: "reps", measurement: "kg" },
  { name: "hammer", count: "reps", measurement: "kg" },
  { name: "kettlebell", count: "reps", measurement: "kg" },
  { name: "leverage machine", count: "reps", measurement: "kg" },
  { name: "medicine ball", count: "reps", measurement: "kg" },
  { name: "olympic barbell", count: "reps", measurement: "kg" },
  { name: "roller", count: "reps", measurement: "" },
  { name: "rope", count: "reps", measurement: "" },
  { name: "skierg machine", count: "time", measurement: "km" },
  { name: "sled machine", count: "reps", measurement: "kg" },
  { name: "smith machine", count: "reps", measurement: "kg" },
  { name: "stability ball", count: "reps", measurement: "kg" },
  { name: "stationary bike", count: "time", measurement: "km" },
  { name: "stepmill machine", count: "time", measurement: "km" },
  { name: "tire", count: "reps", measurement: "kg" },
  { name: "trap bar", count: "reps", measurement: "kg" },
  { name: "upper body ergometer", count: "reps", measurement: "kg" },
  { name: "weighted", count: "reps", measurement: "kg" },
  { name: "wheel roller", count: "reps", measurement: "kg" },
];
